name: EDA
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pandas=1.5.2
  - jupyterlab=3.0.12
  - scikit-learn=1.2
  - matplotlib=3.6.3
  - pyarrow=10.0.1
  - seaborn=0.12.2
  - pip=22.3.1
  - pip:
      - wandb==0.13.9
      - ipywidgets==8.0.4
      - protobuf==3.19.0
      - jupyter==1.0.0
      - mlflow==2.1.1
      - pandas-profiling==3.6.6